const API="/api";
const KEY="portfolio_admin_token";
let projects=[],messages=[],skills=[],journey=[],settings={},activity=[];
let editingSkillId=null,editingJourneyId=null;

const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const token=()=>localStorage.getItem(KEY);
const headers=()=>({Authorization:"Bearer "+token()});

async function api(path,options={}){const r=await fetch(API+path,{...options,headers:{...headers(),...(options.headers||{})}});let d={};try{d=await r.json()}catch{}if(r.status===401){logout();throw new Error("Session expired. Please sign in again.")}if(!r.ok)throw new Error(d.message||"Request failed");return d}

async function login(){try{const email=$("email").value.trim(),password=$("password").value;const r=await fetch(API+"/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.message||"Invalid credentials");localStorage.setItem(KEY,d.token);await start()}catch(e){$("loginMsg").textContent=e.message}}
function logout(){localStorage.removeItem(KEY);location.reload()}

async function start(){if(!token())return;$("login").hidden=true;$("dash").hidden=false;try{await refreshAll();health()}catch(e){console.error(e)}}
async function refreshAll(){[projects,messages,skills,journey,settings,activity]=await Promise.all([api("/projects?admin=1"),api("/contact"),api("/skills"),api("/experience"),api("/settings"),api("/activity")]);renderDashboard();renderProjects();renderMessages();renderSkills();renderJourney();fillSettings();renderActivity()}
async function health(){try{const d=await fetch(API+"/health").then(r=>r.json());$("healthBadge").textContent=`● ${d.storage} / v${d.version}`}catch{$("healthBadge").textContent="Offline"}}

function go(section){document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.section===section));document.querySelectorAll(".page").forEach(p=>p.hidden=p.dataset.page!==section);$("pageTitle").textContent={dashboard:"Dashboard",projects:"Projects",messages:"Contact Messages",content:"Portfolio Content",skills:"Skills",journey:"Experience & Education",settings:"Website Settings",security:"Admin Security",activity:"Activity Logs"}[section]||"Dashboard";window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".nav-btn").forEach(b=>b.addEventListener("click",()=>go(b.dataset.section)));

function renderDashboard(){const published=projects.filter(p=>p.published!==false).length,draft=projects.length-published,unread=messages.filter(m=>m.status!=="read").length;$("totalProjects").textContent=projects.length;$("totalMessages").textContent=messages.length;$("publishedProjects").textContent=published;$("draftProjects").textContent=draft;$("unreadHint").textContent=`${unread} unread`;const last=[...projects].sort((a,b)=>new Date(b.updatedAt||0)-new Date(a.updatedAt||0))[0];$("latestProject").innerHTML=last?`<div class="latest"><b>${esc(last.title)}</b><div class="meta">${esc(last.category||"Web")} · ${last.published!==false?"Published":"Draft"}</div><p class="desc">${esc(last.description||"")}</p></div>`:`<div class="latest">No projects yet.</div>`;const m=messages[0];$("recentMessage").innerHTML=m?`<div class="recent"><b>${esc(m.name)} — ${esc(m.email)}</b><p class="desc">${esc(m.subject||"No subject")}</p><small>${formatDate(m.createdAt)}</small></div>`:`<div class="recent">No messages yet.</div>`}

function newProject(){resetProjectForm();go("projects");$("projectTitle").focus()}
function getProjectData(){return{title:$("projectTitle").value.trim(),category:$("projectCategory").value.trim(),description:$("projectDescription").value.trim(),technologies:$("projectTechnologies").value.split(",").map(x=>x.trim()).filter(Boolean),image:$("projectImage").value.trim(),github:$("projectGithub").value.trim(),demo:$("projectDemo").value.trim(),published:$("projectPublished").checked,featured:$("projectFeatured").checked}}
async function saveProject(e){e?.preventDefault();const id=$("projectId").value;try{const d=getProjectData();const out=await api(id?`/projects/${encodeURIComponent(id)}`:"/projects",{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});$("projectMsg").textContent=id?"Project updated successfully.":"Project added successfully.";resetProjectForm();await refreshAll()}catch(e){$("projectMsg").textContent=e.message}}
function editProject(p){$("projectId").value=p._id||p.id||"";$("projectTitle").value=p.title||"";$("projectCategory").value=p.category||"";$("projectDescription").value=p.description||"";$("projectTechnologies").value=Array.isArray(p.technologies)?p.technologies.join(", "):p.technologies||"";$("projectImage").value=p.image||"";$("projectGithub").value=p.github||"";$("projectDemo").value=p.demo||"";$("projectPublished").checked=p.published!==false;$("projectFeatured").checked=!!p.featured;$("projectFormTitle").textContent="Edit Project";$("projectSubmit").textContent="Update Project";$("cancelProject").hidden=false;window.scrollTo({top:0,behavior:"smooth"})}
async function deleteProject(id){if(!confirm("Delete this project permanently?"))return;try{await api(`/projects/${encodeURIComponent(id)}`,{method:"DELETE"});await refreshAll()}catch(e){alert(e.message)}}
function previewProject(p){const target=p.demo&&p.demo!=="#"?p.demo:(p.image?`/${p.image.replace(/^\//,"")}`:"#");if(target!=="#")window.open(target,"_blank","noopener");else alert("No preview URL is available for this project.")}
function resetProjectForm(){["projectId","projectTitle","projectCategory","projectDescription","projectTechnologies","projectImage","projectGithub","projectDemo"].forEach(id=>$(id).value="");$("projectPublished").checked=true;$("projectFeatured").checked=false;$("projectFormTitle").textContent="Add New Project";$("projectSubmit").textContent="Add Project";$("cancelProject").hidden=true;$("uploadStatus").textContent="";$("projectMsg").textContent=""}
function renderProjects(){const q=$("projectSearch").value.toLowerCase(),filter=$("projectFilter").value;const list=projects.filter(p=>{const text=`${p.title} ${p.category} ${p.description}`.toLowerCase();return(!q||text.includes(q))&&(filter==="all"||(filter==="published"&&p.published!==false)||(filter==="draft"&&p.published===false)||(filter==="featured"&&p.featured))});$("projectList").innerHTML=list.length?list.map(p=>`<article class="project-row"><div class="row-top"><div><h3>${esc(p.title)}</h3><div class="meta">${esc(p.category||"Web")} · <span class="${p.published!==false?"status-published":"status-draft"}">${p.published!==false?"Published":"Draft"}</span>${p.featured?" · ★ Featured":""}</div></div><div class="meta">${formatDate(p.updatedAt||p.createdAt)}</div></div><p class="desc">${esc(p.description||"")}</p><div class="chips">${(p.technologies||[]).map(t=>`<span class="chip">${esc(t)}</span>`).join("")}</div><div class="row-actions"><button class="ghost" onclick='editProject(${JSON.stringify(p)})'>Edit</button><button class="ghost" onclick='previewProject(${JSON.stringify(p)})'>Preview</button><button class="danger" onclick="deleteProject('${esc(p._id||p.id)}')">Delete</button></div></article>`).join(""):`<div class="card">No projects match your filter.</div>`}

async function uploadProjectImage(){const f=$("projectFile").files[0];if(!f)return $("uploadStatus").textContent="Choose an image first.";if(f.size>5*1024*1024)return $("uploadStatus").textContent="Maximum 5 MB.";const reader=new FileReader();reader.onload=async()=>{try{const d=await api("/upload",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({filename:f.name,data:reader.result})});$("projectImage").value=d.path;$("uploadStatus").textContent="Uploaded ✓"}catch(e){$("uploadStatus").textContent=e.message}};reader.readAsDataURL(f)}

function renderMessages(){
  const q=$("messageSearch").value.toLowerCase(),filter=$("messageFilter").value;
  const list=messages.filter(m=>{
    const text=`${m.name} ${m.email} ${m.subject} ${m.message}`.toLowerCase();
    return (!q||text.includes(q))&&(filter==="all"||m.status===filter);
  });
  $("messageList").innerHTML=list.length?list.map(m=>{
    const id=esc(m._id||m.id||"");
    const next=m.status==="read"?"new":"read";
    const label=m.status==="read"?"Unread":"Read";
    return `<article class="message-row ${m.status!=="read"?"unread":""}">
      <div class="row-top"><div><strong>${esc(m.name)}</strong> — ${esc(m.email)}
      <div class="meta">${esc(m.subject||"No subject")} · ${formatDate(m.createdAt)}</div></div>
      <span class="badge">${m.status==="read"?"Read":"Unread"}</span></div>
      <p class="desc">${esc(m.message)}</p>
      <div class="row-actions">
        <button class="ghost" onclick='viewMessage(${JSON.stringify(m)})'>View Full</button>
        <button class="ghost" onclick="toggleMessage('${id}','${next}')">Mark ${label}</button>
        <a class="ghost" href="mailto:${encodeURIComponent(m.email)}?subject=${encodeURIComponent("Re: "+(m.subject||"Your message"))}">Reply</a>
        <button class="danger" onclick="deleteMessage('${id}')">Delete</button>
      </div>
    </article>`;
  }).join(""): `<div class="card">No messages match your filter.</div>`;
}
function viewMessage(m){openModal(`<span class="eyebrow">MESSAGE</span><h2>${esc(m.subject||"No subject")}</h2><p><b>${esc(m.name)}</b> · ${esc(m.email)}</p><p class="desc">${esc(m.message).replace(/\n/g,"<br>")}</p><small>${formatDate(m.createdAt)}</small>`)}
async function toggleMessage(id,status){try{await api(`/contact/${encodeURIComponent(id)}/status`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});await refreshAll()}catch(e){alert(e.message)}}
async function deleteMessage(id){if(!confirm("Delete this message?"))return;try{await api(`/contact/${encodeURIComponent(id)}`,{method:"DELETE"});await refreshAll()}catch(e){alert(e.message)}}

function fillSettings(){const s=settings;$("setName").value=s.name||"";$("setTitle").value=s.title||"";$("setRole").value=s.role||"";$("setEyebrow").value=s.eyebrow||"";$("setHero").value=s.heroDescription||"";$("setAbout").value=s.about||"";$("setLocation").value=s.location||"";$("setDegree").value=s.degree||"";$("setFocus").value=s.focus||"";$("setEmail").value=s.email||"";$("setPhone").value=s.phone||"";$("setProfileImage").value=s.profileImage||"";$("setCv").value=s.cvPath||"";$("setGithub").value=s.social?.github||"";$("setLinkedin").value=s.social?.linkedin||"";$("setInstagram").value=s.social?.instagram||"";$("setX").value=s.social?.x||"";$("setTheme").value=s.theme?.accent||"purple-blue";$("setJwt").value=s.jwtExpiresIn||"8h";$("configStatus").textContent=`Admin password: ${s.adminPasswordConfigured?"configured":"missing"} · JWT secret: ${s.jwtSecretConfigured?"configured":"using fallback"}`}
async function saveSettings(){const payload={name:$("setName").value,title:$("setTitle").value,role:$("setRole").value,eyebrow:$("setEyebrow").value,heroDescription:$("setHero").value,about:$("setAbout").value,location:$("setLocation").value,degree:$("setDegree").value,focus:$("setFocus").value,email:$("setEmail").value,phone:$("setPhone").value,profileImage:$("setProfileImage").value,cvPath:$("setCv").value,jwtExpiresIn:$("setJwt").value,social:{github:$("setGithub").value,linkedin:$("setLinkedin").value,instagram:$("setInstagram").value,x:$("setX").value},theme:{accent:$("setTheme").value}};try{settings=await api("/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});fillSettings();$("contentMsg").textContent="Saved successfully.";setTimeout(()=>$("contentMsg").textContent="",2500)}catch(e){$("contentMsg").textContent=e.message}}

function openSkillForm(skill){editingSkillId=skill?.id||null;$("skillForm").hidden=false;$("skillName").value=skill?.name||"";$("skillIcon").value=skill?.icon||"✦";$("skillLevel").value=skill?.level??80}function closeSkillForm(){editingSkillId=null;$("skillForm").hidden=true}
async function saveSkill(){const d={name:$("skillName").value.trim(),icon:$("skillIcon").value.trim(),level:Number($("skillLevel").value)};try{if(editingSkillId)await api(`/skills/${encodeURIComponent(editingSkillId)}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});else await api("/skills",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});closeSkillForm();await refreshAll()}catch(e){alert(e.message)}}
function renderSkills(){$("skillsList").innerHTML=skills.map(s=>`<div class="skill-admin"><div class="skill-icon">${esc(s.icon||"✦")}</div><b>${esc(s.name)}</b><div class="meta">${Number(s.level)||0}%</div><div class="progress"><i style="width:${Math.max(0,Math.min(100,Number(s.level)||0))}%"></i></div><div class="row-actions"><button class="ghost" onclick='openSkillForm(${JSON.stringify(s)})'>Edit</button><button class="danger" onclick="deleteSkill('${esc(s.id)}')">Delete</button></div></div>`).join("")||`<div class="card">No skills yet.</div>`}async function deleteSkill(id){if(!confirm("Delete this skill?"))return;try{await api(`/skills/${encodeURIComponent(id)}`,{method:"DELETE"});await refreshAll()}catch(e){alert(e.message)}}

function openJourneyForm(item){editingJourneyId=item?.id||null;$("journeyForm").hidden=false;$("journeyId").value=item?.id||"";$("journeyType").value=item?.type||"experience";$("journeyPeriod").value=item?.period||"";$("journeyPlace").value=item?.place||"";$("journeyTitle").value=item?.title||"";$("journeyDescription").value=item?.description||""}function closeJourneyForm(){editingJourneyId=null;$("journeyForm").hidden=true}
async function saveJourney(){const d={type:$("journeyType").value,period:$("journeyPeriod").value,place:$("journeyPlace").value,title:$("journeyTitle").value,description:$("journeyDescription").value};try{if(editingJourneyId)await api(`/experience/${encodeURIComponent(editingJourneyId)}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});else await api("/experience",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});closeJourneyForm();await refreshAll()}catch(e){alert(e.message)}}
function renderJourney(){$("journeyList").innerHTML=journey.map(j=>`<article class="journey-row"><div class="row-top"><div><span class="eyebrow">${esc(j.type||"experience")}</span><h3>${esc(j.title)}</h3><div class="meta">${esc(j.place||"")} · ${esc(j.period||"")}</div></div></div><p class="desc">${esc(j.description||"")}</p><div class="row-actions"><button class="ghost" onclick='openJourneyForm(${JSON.stringify(j)})'>Edit</button><button class="danger" onclick="deleteJourney('${esc(j.id)}')">Delete</button></div></article>`).join("")||`<div class="card">No experience or education items.</div>`}async function deleteJourney(id){if(!confirm("Delete this item?"))return;try{await api(`/experience/${encodeURIComponent(id)}`,{method:"DELETE"});await refreshAll()}catch(e){alert(e.message)}}

async function changePassword(){const a=$("currentPassword").value,b=$("newPassword").value,c=$("confirmPassword").value;if(b!==c)return $("passwordMsg").textContent="New passwords do not match.";try{const d=await api("/admin/change-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword:a,newPassword:b})});alert(d.message);logout()}catch(e){$("passwordMsg").textContent=e.message}}
async function logoutAll(){if(!confirm("Logout every admin session?"))return;try{await api("/admin/logout-all",{method:"POST"});alert("All sessions revoked.");logout()}catch(e){alert(e.message)}}
async function regenerateSecret(){if(!confirm("Regenerate JWT secret? Every admin session will be revoked."))return;try{const d=await api("/admin/regenerate-secret",{method:"POST"});alert(d.message);logout()}catch(e){alert(e.message)}}
function renderActivity(){$("activityList").innerHTML=activity.length?activity.map(a=>`<div class="activity"><b>${esc(a.action)}</b><span>${esc(a.detail||"")} · ${formatDate(a.createdAt)}</span></div>`).join(""):`<p class="muted">No activity yet.</p>`}
function formatDate(v){if(!v)return"";const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString()}
function openModal(html){$("modalBody").innerHTML=html;$("modal").hidden=false}function closeModal(){$("modal").hidden=true;$("modalBody").innerHTML=""}
$("projectForm").addEventListener("submit",saveProject);document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});document.addEventListener("DOMContentLoaded",start);
